name: Home
author: Kevin George
main: me.kevingeorge.Home.Home
version: 1.0
api-version: 1.18
commands:
   sethome:
      description: Set your home to teleport to later.
      usage: "/sethome"
   home:
      description: Teleport to your home.
      usage: "/home"